#!/usr/bin/env python3
"""High-budget baseline screen: every problem, both goal directions.

This is step 2 of docs/EXPECTATIONS.md. It exists because a 30s screen mislabeled
ROB026-1 and ROB033-1 as unsolved when they need 419s and 782s, and three
experiment designs were built on that bad screen before it was caught. It also
runs both goal directions because direction alone flips those two problems
between solved and GaveUp.

Its outputs are the paired baselines every later hinted run needs, the label
source for rule-usefulness training, and -- as ROB033-1 showed -- possibly a few
newly solved problems on its own.

Resumable: results already in results.jsonl are skipped, so it is safe to kill
and restart. Writes docs/RUNS.md after every completed job.
"""
import argparse
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from overtone import batch, runner                               # noqa: E402
from overtone.runner import ALWAYS, BASE_FLAGS                   # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DIRECTIONS = ["--flatten-goal", "--no-flatten-goal"]


def job_id(problem: str, direction: str) -> str:
    return f"{problem}|{direction}"


def run_job(args) -> dict:
    problem, direction, budget, outdir, keep_output = args
    # One input file per job, not per problem: the two goal directions run in
    # separate workers and would otherwise share a path and race.
    tag = direction.replace("--", "")
    path = runner.write_problem(
        problem,
        Path(outdir) / "inputs" / batch.INPUT_STEM.format(problem=problem, tag=tag))
    # use_max_time stays False: the 592 existing screen records were produced
    # with an external timeout, and adding --max-time would change the search.
    r = runner.run(path, [*BASE_FLAGS, direction], budget, problem=problem)
    if keep_output and r.proved:
        d = Path(outdir) / "proofs"
        d.mkdir(parents=True, exist_ok=True)
        (d / batch.PROOF_STEM.format(problem=problem, tag=tag)).write_text(r.output)
    return {
        "id": job_id(problem, direction),
        "problem": problem,
        "direction": direction,
        "budget": budget,
        "result": r.status,
        "proved": r.proved,
        "cpu": round(r.cpu, 2),
        "wall": round(r.wall, 2),
        "finished": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }


MARKER = "<!-- BEGIN GENERATED -- everything below is rewritten each job -->"

DEFAULT_HEADER = """# Runs

Live tracker for the high-budget baseline screen (step 2 of
`docs/EXPECTATIONS.md`). Every problem, both goal directions, no hints.

This is also the pre-registration: the candidate set and budget are fixed here
*before* any hinted or learned run, so that a later flip cannot be explained by
having chosen the problems afterwards.

Add notes above the marker line -- they survive. Everything below it is
regenerated by `scripts/screen.py` after every completed job.

"""


def write_markdown(md_path: Path, done: dict, planned: list, meta: dict):
    """Regenerate the tracker below MARKER, preserving anything above it.

    The tables are derived and rewritten wholesale, but the top of the file is
    left alone so notes added while a multi-hour screen runs survive.
    """
    by_problem = {}
    for rec in done.values():
        by_problem.setdefault(rec["problem"], {})[rec["direction"]] = rec

    solved, unsolved, partial = [], [], []
    for problem, dirs in by_problem.items():
        if len(dirs) < 2:
            continue
        f, nf = dirs.get("--flatten-goal"), dirs.get("--no-flatten-goal")
        if f["proved"] or nf["proved"]:
            best = min((d for d in (f, nf) if d["proved"]), key=lambda d: d["cpu"])
            only = "both" if f["proved"] and nf["proved"] else (
                "flatten" if f["proved"] else "no-flatten")
            solved.append((best["cpu"], problem, best["direction"], only))
        else:
            unsolved.append((problem, f["result"], nf["result"]))
    for problem, dirs in by_problem.items():
        if len(dirs) == 1:
            partial.append(problem)

    solved.sort(reverse=True)
    unsolved.sort()
    total = len(planned)
    lines = [
        MARKER,
        "",
        f"- started `{meta.get('started', '?')}`",
        f"- budget **{meta.get('budget')}s** per problem per goal direction",
        f"- flags `{' '.join(BASE_FLAGS)}` + direction + "
        f"`{' '.join(ALWAYS)}`, no hints",
        f"- problem list `{meta.get('problems', '?')}`",
        f"- progress **{len(done)}/{total}** jobs "
        f"({len(by_problem)} problems touched, {len(solved)} complete pairs solved)",
        f"- updated `{datetime.now(timezone.utc).isoformat(timespec='seconds')}`",
        "",
        "## Solved",
        "",
        "Slowest first -- the top of this table is the near-frontier band that "
        "any speedup can plausibly extend.",
        "",
        "| problem | best cpu | direction | solved by |",
        "|---|---|---|---|",
    ]
    for cpu, problem, direction, only in solved:
        lines.append(f"| {problem} | {cpu:.1f}s | {direction} | {only} |")
    if not solved:
        lines.append("| _none yet_ | | | |")

    lines += [
        "",
        "## Resisted both directions",
        "",
        f"{len(unsolved)} problems. These are candidates for hints, not for "
        "speedups.",
        "",
        "| problem | --flatten-goal | --no-flatten-goal |",
        "|---|---|---|",
    ]
    for problem, f, nf in unsolved:
        lines.append(f"| {problem} | {f} | {nf} |")
    if not unsolved:
        lines.append("| _none yet_ | | |")

    if partial:
        lines += ["", f"## In flight", "",
                  f"{len(partial)} problems have one direction done: "
                  + ", ".join(sorted(partial)[:20])
                  + (" ..." if len(partial) > 20 else "")]

    lines += ["", "---", "",
              f"Raw results: `{meta.get('results', 'logs/screen/results.jsonl')}`"]

    header = DEFAULT_HEADER
    if md_path.exists():
        existing = md_path.read_text()
        if MARKER in existing:
            header = existing.split(MARKER, 1)[0].rstrip() + "\n\n"
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(header + "\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--problems", type=Path,
                    default=ROOT / "data" / "lists" / "screen.txt",
                    help="file of problem names, one per line")
    ap.add_argument("--budget", type=int, default=1000,
                    help="seconds per problem per direction (default 1000)")
    ap.add_argument("--workers", type=int, default=12,
                    help="concurrent twee processes (default 12)")
    ap.add_argument("--outdir", type=Path, default=ROOT / "logs" / "screen")
    ap.add_argument("--markdown", type=Path, default=ROOT / "docs" / "RUNS.md")
    ap.add_argument("--keep-proofs", action="store_true",
                    help="save twee output for solved problems (label source)")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    if not a.problems.exists():
        sys.exit(f"{a.problems} does not exist")
    names = [l.strip() for l in a.problems.read_text().splitlines()
             if l.strip() and not l.startswith("#")]
    planned = [(n, d) for n in names for d in DIRECTIONS]

    a.outdir.mkdir(parents=True, exist_ok=True)
    results_path = a.outdir / "results.jsonl"
    done = batch.load_done(results_path)
    todo = [(n, d, a.budget, str(a.outdir), a.keep_proofs)
            for n, d in planned if job_id(n, d) not in done]

    def rel(p: Path) -> str:
        """Repo-relative when inside the repo, absolute otherwise."""
        try:
            return str(p.relative_to(ROOT))
        except ValueError:
            return str(p)

    meta = {"started": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "budget": a.budget, "problems": rel(a.problems),
            "results": rel(results_path)}

    print(f"{len(names)} problems x {len(DIRECTIONS)} directions = {len(planned)} jobs")
    print(f"  {len(done)} already done, {len(todo)} to run")
    print(f"  budget {a.budget}s, {a.workers} workers")
    worst = len(todo) * a.budget / a.workers / 3600
    print(f"  worst case {worst:.1f}h wall ({len(todo) * a.budget / 3600:.0f} cpu-hours)")
    if a.dry_run:
        return
    if not todo:
        write_markdown(a.markdown, done, planned, meta)
        print("nothing to do; markdown refreshed")
        return

    started = time.monotonic()

    def report(i, rec, done):
        write_markdown(a.markdown, done, planned, meta)
        mark = "PROVED" if rec["proved"] else rec["result"]
        print(f"  [{i}/{len(todo)}] {rec['problem']:<12} "
              f"{rec['direction']:<18} {mark:<18} {rec['cpu']:7.1f}s "
              f"({(time.monotonic() - started) / 60:.0f}m elapsed)", flush=True)

    done = batch.sweep(todo, run_job, results_path, workers=a.workers,
                       on_result=report)

    print(f"\ndone in {(time.monotonic() - started) / 3600:.2f}h -> {a.markdown}")


if __name__ == "__main__":
    main()
